import { Product, Category } from "@/types/models";

export const CATEGORIES: Category[] = [
  {
    id: "cat-01",
    slug: "signature-collection",
    name: "Signature Collection",
    description: "The core olfactory identities of Nascent. Timeless, clinical, and precise.",
    imageUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "cat-02",
    slug: "nocturnal-collection",
    name: "Nocturnal Collection",
    description: "Fragrances that inhabit the dark hours. Dense, architectural, uncompromising.",
    imageUrl: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "cat-03",
    slug: "discovery-sets",
    name: "Discovery Sets",
    description: "Curated selections to explore the Nascent spectrum.",
    imageUrl: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=1000",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod-01",
    slug: "walk-in-garden",
    name: "Walk in Garden",
    description: "A journey through a blooming sanctuary. Cold, structural floral notes grounded in stark earthy undertones. An uncompromising interpretation of nature.",
    price: 185,
    stock: 24,
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1000",
    ],
    scentNotes: ["Floral", "Fresh"],
    categoryId: "cat-01",
    isFeatured: true,
    collection: "SIGNATURE COLLECTION // 001",
    intensity: "Moderate",
    volume: "50ml Extrait de Parfum",
    topNote: "Bergamot, White Tea",
    heartNote: "Jasmine, Neroli",
    baseNote: "Vetiver, Cold Musk",
  },
  {
    id: "prod-02",
    slug: "phantom-elixir",
    name: "Phantom Elixir",
    description: "An architectural study in shadow. A stark, uncompromising fragrance that strips away the superfluous to reveal a cold, precise core. It speaks of brutalist concrete, midnight air, and absolute clarity.",
    price: 220,
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=1000",
    ],
    scentNotes: ["Oriental", "Intense"],
    categoryId: "cat-02",
    isFeatured: true,
    collection: "NOCTURNAL COLLECTION // 004",
    intensity: "Intense",
    volume: "50ml Extrait de Parfum",
    topNote: "Sichuan Pepper, Cardamom",
    heartNote: "Smoked Jasmine Absolute",
    baseNote: "Aged Indonesian Oud",
  },
  {
    id: "prod-03",
    slug: "midnight-oud",
    name: "Midnight Oud",
    description: "The darkest expression in our nocturnal range. Dense resinous oud fused with cold vetiver and a trace of birch smoke. A fragrance for those who inhabit the dark hours.",
    price: 240,
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=1000",
    ],
    scentNotes: ["Woody", "Intense"],
    categoryId: "cat-02",
    isFeatured: true,
    collection: "NOCTURNAL COLLECTION // 002",
    intensity: "Intense",
    volume: "50ml Extrait de Parfum",
    topNote: "Black Pepper, Cypriol",
    heartNote: "Birch Smoke, Leather",
    baseNote: "Aged Oud, Amber",
  },
  {
    id: "prod-04",
    slug: "santal-blanc",
    name: "Santal Blanc",
    description: "A study in restraint. Pale sandalwood stripped of sentimentality — clean, cold, and precise. The olfactory equivalent of an empty white room.",
    price: 195,
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=1000",
    ],
    scentNotes: ["Woody", "Subtle"],
    categoryId: "cat-01",
    isFeatured: false,
    collection: "SIGNATURE COLLECTION // 003",
    intensity: "Subtle",
    volume: "50ml Extrait de Parfum",
    topNote: "White Cedar, Aldehydes",
    heartNote: "Sandalwood, Orris Root",
    baseNote: "White Musk, Ambroxan",
  },
  {
    id: "prod-05",
    slug: "vetiver-absolute",
    name: "Vetiver Absolute",
    description: "Haitian vetiver in its most concentrated form. Earthy, smoky, and achingly precise. A linear fragrance that refuses embellishment.",
    price: 210,
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&q=80&w=1000",
    ],
    scentNotes: ["Fresh", "Moderate"],
    categoryId: "cat-01",
    isFeatured: false,
    collection: "SIGNATURE COLLECTION // 005",
    intensity: "Moderate",
    volume: "50ml Extrait de Parfum",
    topNote: "Grapefruit, Green Accord",
    heartNote: "Clary Sage, Vetiver Heart",
    baseNote: "Haitian Vetiver, Cedarwood",
  },
];
